#ifndef _DEFINES_H_
#define _DEFINES_H_

// SDL
#define SDL_INIT_FLAGS          SDL_INIT_VIDEO
#define SDL_WINDOW_FLAGS        SDL_WINDOW_SHOWN 
#define SDL_RENDER_FLAGS        SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE | SDL_RENDERER_PRESENTVSYNC

// Game
#define GAME_W 224
#define GAME_H 256
#define GAME_DEFAULT_SCALE 2

#endif //_DEFINES_H_
